### ISSUE TITLE
100% progress displayed despite there are missing keys

### ISSUE THREAD

**Issue by Nonouf** [texterify/texterify#124]
I've seen this bug for a while now. The dashboard is always displaying 100% progress despite I have several missing translations. See below, French is the base language, but Dutch is missing a lot of translations and is displaying 100% progress:

<img width="1159" alt="Screenshot 2022-08-16 at 09 03 55" src="https://user-images.githubusercontent.com/2992866/184818914-035b30eb-2c22-4854-82a5-98de41f8d27c.png">

Is there any way to fix that ?

**Comment by chrztoph** [comment]
Hey, can you somehow reproduce this in a new project? I'm not able to do it.
Would help me with fixing this issue. Thank you! 🙂

**Comment by Nonouf** [comment]
@chrztoph I'm on the free plan at the moment, I can't create a second project. Sorry!

**Comment by Nonouf** [comment]
@chrztoph Any updates on this ? Did you manage to reproduce the problem?

**Comment by chrztoph** [comment]
Yes, we will probably deploy a fix for this next week.

**Comment by Nonouf** [comment]
@chrztoph The last update fixed the issue, thanks!
