### ISSUE TITLE
Failed to update Texterify

### ISSUE THREAD

**Issue by Nonouf** [texterify/texterify#132]
I'm trying to update from version 1.0.7 to 1.2.0 but I always get the following error message on Docker :

> Cannot start Docker Compose application. Reason: Error invoking remote method 'compose-action': Error: Command failed: docker-compose --file "docker-compose.yml" --project-name "texterify-docker-compose-setup" --project-directory "/Users/jenkins/repositories/texterify-docker-compose-setup" up -d time="2022-10-27T17:43:54+02:00" level=warning msg="volume texterify-database: volume.external.name is deprecated in favor of volume.name" time="2022-10-27T17:43:54+02:00" level=warning msg="volume texterify-assets: volume.external.name is deprecated in favor of volume.name" app Pulling sidekiq Pulling app Error sidekiq Error Error response from daemon: Get "https://registry-1.docker.io/v2/": EOF

I'm far from being an expert with Docker. I'd appreciate a bit of help.

**Comment by Nonouf** [comment]
We managed to update Texterify by following the [doc](https://docs.texterify.com/installation/updating-the-service).
Would be great to update the README ;)

**Comment by chrztoph** [comment]
Oh, you are right. Thanks for pointing this out. I will update it.
