### ISSUE TITLE
Unset plurals are exported as empty string

### ISSUE THREAD

**Issue by aaachris** [texterify/texterify#141]
If I export a key with pluralization enabled, plural forms which i don't define are exported as empty strings.
Defining only other and one i get the following output:

```
"test_plural_key": {
 "other": "{} cars,
 "zero": "",
 "one": "One car",
 "two": "",
 "few": "",
 "many": ""
},
```

My translation framework returns an empty string if provide 0 as argument.
An option to enable/disable exporting unset plural forms would be awesome.

**Comment by chrztoph** [comment]
This feature has been implemented and will be available in the next release.
Thank you for your feedback.
