### ISSUE TITLE
Is there CSV export format?

### ISSUE THREAD

**Issue by dimmduh** [texterify/texterify#143]
How to export to csv?
It seems no industry standart format.

**Comment by chrztoph** [comment]
Hey, unfortunately not at the moment.
In what CSV export format and for which library/tool do you want to export your translations? If you could tell me this adding it is probably not a big deal.

**Comment by dimmduh** [comment]
Im in gamedev. Google speedsheet, many tools and plugins in game engine (unity) always accept csv, other formats is not widely used.

**Comment by yevgenypats** [comment]
Hey team 👋 ! Im Yevgeny, maintainer and founder @ [CloudQuery](https://github.com/cloudquery/cloudquery), an open source high performance ELT framework.

We would love to help with an initial version of CloudQuery [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), if you can help us maintain it. It should solve this issue and enable your users to sync texterify data to any database/datalake of the growing number of [CQ destinations](https://www.cloudquery.io/docs/plugins/destinations/overview).

See similar thing we did with [Plausible API](https://www.cloudquery.io/docs/plugins/sources/plausible/overview), [Plausible Docs](https://plausible.io/docs/integration-guides#bigquery) and [discussion](https://github.com/plausible/analytics/discussions/1777)

**Comment by chrztoph** [comment]
Hey, we have added the possibility to export the translations as csv. 🙂

@yevgenypats Please open a separate ticket.
