### ISSUE TITLE
Support of nested JSON

### ISSUE THREAD

**Issue by pumano** [texterify/texterify#30]
I have JSON structure with nesting : 

```
{
  "home": {
     "title": "title here"
  }
}
```

but after import i only get "home" with json as text as value.

Did you have plans for support nested JSON structures?

P. S. thanks for good app

**Comment by chrztoph** [comment]
Yes, it is planned to support nested JSON.
For now only flat JSON works.

Thanks for the feedback. 👍

**Comment by pumano** [comment]
Would love to use your app inside my company, when nested structures come)

**Comment by mmailaender** [comment]
@chrztoph is that not already working since january this year? Or is this something different here?

**Comment by chrztoph** [comment]
Sorry, forgot about this issue here. Support for nested JSON has been added since a while.

**Comment by ervansanjaya** [comment]
Hi @chrztoph I think I'm lost in the documentation on how to implement this. Can you please refer me the how-tos?
Thanks
