### ISSUE TITLE
WordPress / `.pot` support

### ISSUE THREAD

**Issue by matzeeable** [texterify/texterify#59]
Hey Texterify team!

Your solution looks really promising, and we are currently investigating to automate our localization extraction, versioning and management to get a complete continuous localization system.

That is what we have achieved so far:

1. We push changes to our WordPress plugin via GIT
1. Our CI enters the job `build plugin`
1. We extract language / i18n keys from source files to a `.pot` file
1. We push the `.pot` file to a translation management tool, so we can translate it (**this part is missing**)
1. We pull the `.po` files from the translation management tool (**this part is missing**)
1. The plugin is built with language files

We want to avoid holding any translation data in our GIT repository.

Step 4 and 5 is prepared in our CI, so we can introduce a simple CLI call that fits the needs.

Is this something Texterify can be used for?

Regards
Matthew 😊

**Comment by chrztoph** [comment]
Closed in favor of #61.
