### ISSUE TITLE
Can not launch docker compose locally

### ISSUE THREAD

**Issue by DblK** [texterify/texterify#62]
Hi,

I successfully tested the product using the other repository (https://github.com/texterify/texterify-docker-compose-setup).
However I can not launch the `docker-compose up` here.

I do have the following issue:
```
#24 203.2 The resolved_paths option has been deprecated. Use additional_paths instead.
#24 203.2 Compiling...
#24 559.6 Compilation failed:
#24 559.6
#24 559.7 The resolved_paths option has been deprecated. Use additional_paths instead.
------
executor failed running [/bin/bash -c SECRET_KEY_BASE=`bin/rails secret`     RAILS_ENV=$RAILS_ENV     COMMIT_HASH=$COMMIT_HASH     SENTRY_SOURCE_MAPS_AUTH_TOKEN=$SENTRY_SOURCE_MAPS_AUTH_TOKEN     SENTRY_SOURCE_MAPS_ORGANIZATION=$SENTRY_SOURCE_MAPS_ORGANIZATION     SENTRY_SOURCE_MAPS_PROJECT=$SENTRY_SOURCE_MAPS_PROJECT     PROPRIETARY_MODE=$PROPRIETARY_MODE     STRIPE_PUBLIC_API_KEY=$STRIPE_PUBLIC_API_KEY     TEXTERIFY_PAYMENT_SERVER=$TEXTERIFY_PAYMENT_SERVER     SENTRY_DSN_FRONTEND=$SENTRY_DSN_FRONTEND     bundle exec rails assets:precompile]: exit code: 1
ERROR: Service 'app' failed to build : Build failed
```

I wanted to fix some tweaks and add some ideas but can not start it right now...
Can you give me any hints?

**Comment by chrztoph** [comment]
Hey,

I'm sorry you are having problems with the setup.

Could you provide more information using `docker-compose logs`?

My first guess would be that Docker does not have enough memory to compile the assets. Webpacker consumes a huge amount during initial compilation so increasing that limit might help.

**Comment by DblK** [comment]
I did set up a higher limit and beside still have an error with `resolved_path` vs `additional_paths`, it's now working locally within docker.
Thanks!

**Comment by chrztoph** [comment]
That `resolved_path/additional_paths` is a warning and has currently no impact. We will address this during the next major upgrade of packages.

Great that it is working now.
