### ISSUE TITLE
Empty page when using the IP instead of a domain

### ISSUE THREAD

**Issue by Nonouf** [texterify/texterify#71]
Hi,

I have installed the on-premise version and I've set localhost for the env variables APP_HOST, MAILER_HOST and ASSET_HOST. Everything is working fine when I open localhost in my browser. 
However, when I use the machine's IP address instead of "localhost" in my browser, I always get a blank screen. Am I missing something with the config ? 

I've also tried setting the IP address instead of localhost in the env file, but then I get the same result when I try to reach the website using the IP address and using localhost.

**Comment by chrztoph** [comment]
Hey,

how does your setup look like? Do you want to connect to the instance directly via IP over the network/internet or do you mean locally (127.0.0.1:3000)?

What does the browser dev tools say? Are the JS files loaded or are there any errors in the browser console or network tab?

Thank you. 🙂

**Comment by Nonouf** [comment]
> how does your setup look like? 

The .env file looks like this :
```
TEXTERIFY_TAG=v1.0.7

APP_HOST=<host_ip_address> # I've tried setting the IP address and also using `localhost`
MAILER_HOST=localhost
ASSET_HOST=localhost
EMAIL_CONFIRMATION_REQUIRED=false

SMTP_ADDRESS=127.0.0.1
SMTP_PORT=
SMTP_DOMAIN=
SMTP_USER_NAME=
SMTP_PASSWORD=
SMTP_AUTHENTICATION=
SMTP_ENABLE_STARTTLS_AUTO=
SMTP_OPENSSL_VERIFY_MODE=
SMTP_TLS=

DEEPL_API_TOKEN=

GOOGLE_CLOUD_PROJECT=
GOOGLE_CLOUD_KEYFILE=
GOOGLE_CLOUD_OTA_BUCKET_NAME=

http_proxy=<our_internal_proxy>
http_proxy_deepl=
```

Otherwise, I use the default config. The only thing I changed is the port for the web app, which I set to 8080:80.

> Do you want to connect to the instance directly via IP over the network/internet or do you mean locally (127.0.0.1:3000)?

I mean that I want to connect over the network. I've tried to access the browser both on the machine hosting texterify and on another machine. In both cases I can't access it through another machine. I have the same result on the hosting machine when I set an IP address in APP_HOST. However when I set `localhost` in APP_HOST, it's working but only on the hosting machine.

> What does the browser dev tools say?

The only error I get in the browser is `Error: Promised response from onMessage listener went out of scope 2 background.js:841:170`

**Comment by Nonouf** [comment]
@chrztoph I managed to fix the issue. My env file was actually missing the port, see below :
```
APP_HOST=<host_ip_address>:8080
MAILER_HOST=<host_ip_address>:8080
ASSET_HOST=<host_ip_address>:8080
```

**Comment by chrztoph** [comment]
Oh, nice you fixed it yourself before I could take a look. 🎉
