### ISSUE TITLE
Several Feature requests

### ISSUE THREAD

**Issue by Nonouf** [texterify/texterify#72]
I have several feature requests, not sure if it's something you could add, but I'm curious to have your opinion.

- Platforms have sometimes different ways of displaying placeholders. For example, iOS uses %@ whereas Android uses %s and %d. The export method should automatically use the right placeholder for the platform.
- It'd be great to have an option to be able to either apply uppercase or lowercase to the keys when exporting. Sometimes different platforms follows different guidelines / best practices. You could even go further by allowing other formatting options such as camel case, snake case... 
- Allowing an empty string for some translation. e.g. we have the situation where one key has a text in French but none in Dutch therefore it always says that a translation is missing in Dutch, which isn't actually true.

**Comment by chrztoph** [comment]
Hi!

- We are already working on this one. Meanwhile you can work around by making use oft Post Processing where you can replace certain placeholders with other placeholders at export time. The other thing you can do is to overwrite the translations for a specific export configuration by clicking on the `+` on the keys site. Both are not intended to be used for this but can meanwhile be used as a workaround.
- Can you give me an example what you mean here?
- Good idea! We will add that.

Thank you for your feedback!

**Comment by Nonouf** [comment]
Thanks! I'll look into using the workaround.

> Can you give me an example what you mean here?

A concrete example we have at the moment is that our iOS app uses uppercased keys whereas our Android project uses lowercased keys. I know we could easily write a script on our end that will change it from uppercase to lowercase (or the other way around), but I think it'd be nice to have some sort of customisation directly in the export tool.

In our case, all our keys are snake case on both platforms, but I've seen other projects where the keys would use different formats on different platforms.

I hope it makes sense :)

**Comment by chrztoph** [comment]
Closing this in favor of the 3 tickets #75, #76 and #77.

Thank you again for the feedback. 🙂
