### ISSUE TITLE
React integration and API

### ISSUE THREAD

**Issue by TheSinding** [texterify/texterify#84]
Hi, very impressive project you have and nicely done! 

We are considering if it would work in our stack, so we have a couple of questions.

- Will it integrate into React somehow?

I see you have a node api integration, but it looks very limited.
- Is it possible to get translations from the API by single keys and locale ? 
- Is it possible to query all the keys from a language ?
- Does it allow for exporting through the API ? 

Edit:
I just saw now it's in the CLI integration.
- Is it possible for us to build it our self? or possibly we could maybe contribute to your node-api package?
- Is there some documentation for the API ? Like OpenAPI docs, swagger, etc?

Thanks !

**Comment by chrztoph** [comment]
Hi, thank you for the kind words. 🙂

> Will it integrate into React somehow?

There is an own FormatJS exporter, a JSON exporter and even some special TypeScript file format for old TypeScript projects where importing JSON directly was not possible. We even built it with the background of being React developers. So it will definitely work with React. 😉

> Is it possible for us to build it our self? or possibly we could maybe contribute to your node-api package?
> Is there some documentation for the API ? Like OpenAPI docs, swagger, etc?

Everything that can be done in the web app can also be done through the API. In fact the web app just consumes the public API. I would love to see your contribution to the [texterify-api-node](https://github.com/texterify/texterify-api-node) package. Unfortunately there is no API documentation at the moment but it is on our [roadmap](https://github.com/texterify/texterify/projects/1). In the meanwhile you can check out the API files that are used in the web app [here](https://github.com/texterify/texterify/tree/master/app/javascript/components/api/v1). Let me know if you need help understanding them, but it should not be that hard I guess and adding them to the `texterify-node-api` project is more or less copy and paste from the API files.

Thank you!

**Comment by TheSinding** [comment]
Thanks, we'll have a look :) !
