### ISSUE TITLE
Unable to setup the project with Remote Container + VSC

### ISSUE THREAD

**Issue by Francis-Tao-jinjin** [texterify/texterify#92]
<img width="912" alt="Screenshot 2022-01-03 at 1 11 34 PM" src="https://user-images.githubusercontent.com/17539265/147901207-3ccd776c-7af8-4020-8fb9-f2cefeaaa22a.png">

Every time I open the project, it throws this error. I couldn't find any related information from google. If anyone knows how to solve this problem, I will be much grateful.

**Comment by krisrefs** [comment]
Are you following the tutorial? https://docs.texterify.com/installation 

Remember to do: `docker-compose up --always-recreate-deps`

**Comment by chrztoph** [comment]
It seems like you are missing the network.

Try to run `docker network create texterify-network`.

**Comment by chrztoph** [comment]
Closing this issue. Feel free to reopen if you still have problems.
